apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml

images:
- name: 194768394447.dkr.ecr.us-east-1.amazonaws.com/workshop-2/production/backend
  newName: 194768394447.dkr.ecr.us-east-1.amazonaws.com/workshop-2/production/backend
  newTag: f39d9a791f13bac134a11a6d1796debca840edc2
