apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml

images:
- name: 194768394447.dkr.ecr.us-east-1.amazonaws.com/workshop-2/production/backend
  newName: 194768394447.dkr.ecr.us-east-1.amazonaws.com/workshop-2/production/backend
  newTag: d76e7e9a31bc986f0f6d2680d551b1c46653b06f
